import assert from 'node:assert/strict';
import { upgradePriceRange } from '../src/lib/upgrade.ts';

const base = process.argv[2] || 'http://localhost:3000';
assert.ok(['localhost', '127.0.0.1'].includes(new URL(base).hostname), 'Checks use only an isolated local profile');
let cookie = '';
async function request(path, body, expected = 200) {
  const response = await fetch(base + path, { headers: { Cookie: cookie, ...(body ? { 'Content-Type': 'application/json' } : {}) }, ...(body ? { method: 'POST', body: JSON.stringify({ requestId: crypto.randomUUID(), ...body }) } : {}) });
  const setCookie = response.headers.get('set-cookie');
  if (setCookie) cookie = setCookie.split(';')[0];
  const text = await response.text();
  assert.equal(response.status, expected, path + ': ' + text.slice(0, 240));
  return response.headers.get('content-type')?.includes('json') ? JSON.parse(text) : text;
}
for (const path of ['/', '/upgrade', '/contract', '/profile', '/case/einstein', '/case/spiderman', '/profile/stats', '/profile/collections', '/profile/achievements', '/profile/showcase', '/art/cases/einstein.png', '/art/cases/spiderman.png', '/art/cases/mendeleyev.png']) await request(path);
await request('/api/state');
const topup = await request('/api/state', { type: 'topup', amount: 10000000 });
assert.equal(topup.state.balance, 0);
assert.equal(topup.state.pending.amount, 10000000);
await new Promise(resolve => setTimeout(resolve, 5100));
let current = await request('/api/state');
assert.equal(current.state.balance, 10000000);
assert.equal(current.state.pending, null);
for (const [min, max] of [[100, 200], [114, 120], [0, 0], [100.01, 100.99]]) {
  const result = await request(`/api/items?min=${min}&max=${max}&limit=200`);
  assert.ok(result.items.every(i => i.price >= min && i.price <= max));
}
for (const query of ['min=200&max=100', 'min=-1', 'max=no', 'min=Infinity', 'max=Infinity']) await request('/api/items?' + query, undefined, 400);
for (const percent of [1, 25, 50, 75]) {
  const range = upgradePriceRange(10000, percent);
  const targets = await request(`/api/items?min=${range.min / 100}&max=${range.max / 100}&sort=desc&limit=1`);
  assert.ok(targets.items.length, 'Available target for ' + percent);
  const balance = current.state.balance;
  current = await request('/api/state', { type: 'upgrade', extra: 10000, target: targets.items[0].id });
  const expectedChance = Math.min(.75, 10000 / Math.round(targets.items[0].price * 100) * .9);
  assert.equal(current.result.chance, expectedChance);
  assert.ok(current.result.chance + 1e-12 >= percent / 100);
  assert.equal(current.state.balance, balance - 10000);
}
const opened = await request('/api/state', { type: 'open', caseId: 'einstein', count: 10 });
assert.equal(opened.result.items.length, 10);
assert.equal(opened.state.opens, 10);
assert.ok(opened.state.history[0].label.startsWith('Импульс'));
assert.equal(opened.state.progress.stats.caseOpens, 10);
assert.equal(opened.state.progress.stats.caseSpent, 69000);
assert.equal(opened.state.progress.stats.caseReturn, opened.result.items.reduce((sum, i) => sum + i.value, 0));
const protectedItem = opened.result.items[0];
const details = await request('/api/items/' + protectedItem.id);
assert.equal(details.item.id, protectedItem.id);
assert.ok(details.cases.some(c => c.id === 'einstein'));
assert.ok(details.cases.every(c => c.chance > 0 && c.image.startsWith('/art/')));
await request('/api/items/-1', undefined, 404);
current = await request('/api/state', { type: 'lock', ids: [protectedItem.uid], locked: true });
assert.ok(current.state.progress.locked.includes(protectedItem.uid));
const lockedSnapshot = JSON.stringify(current.state);
await request('/api/state', { type: 'sell', ids: [protectedItem.uid] }, 400);
await request('/api/state', { type: 'upgrade', ids: [protectedItem.uid], target: details.item.id }, 400);
await request('/api/state', { type: 'contract', ids: opened.result.items.slice(0, 3).map(i => i.uid) }, 400);
assert.equal(JSON.stringify((await request('/api/state')).state), lockedSnapshot);
await request('/api/state', { type: 'showcase', ids: opened.result.items.slice(0, 9).map(i => i.uid) }, 400);
await request('/api/state', { type: 'showcase', ids: [protectedItem.uid], title: 'x'.repeat(49) }, 400);
await request('/api/state', { type: 'showcase', ids: [protectedItem.uid], title: 'Тестовая витрина' });
await request('/api/state', { type: 'appearance', frame: 'unknown' }, 400);
await request('/api/state', { type: 'appearance', frame: 'violet' });
current = await request('/api/state');
assert.equal(current.state.progress.title, 'Тестовая витрина');
assert.equal(current.state.progress.frame, 'violet');
assert.deepEqual(current.state.progress.showcase, [protectedItem.uid]);
await request('/api/state', { type: 'lock', ids: [protectedItem.uid], locked: false });
let testedSkin = false;
for (const owned of opened.result.items) {
  const range = upgradePriceRange(owned.value, 25);
  if (!range) continue;
  const targets = await request(`/api/items?min=${range.min / 100}&max=${range.max / 100}&sort=desc&limit=1`);
  if (!targets.items.length) continue;
  current = await request('/api/state', { type: 'upgrade', ids: [owned.uid], target: targets.items[0].id, chance: .25 });
  assert.equal(current.result.chance, .25);
  assert.ok(!current.state.inventory.some(i => i.uid === owned.uid));
  testedSkin = true; break;
}
assert.ok(testedSkin, 'Skin-backed upgrade verified');
const beforeInvalid = current.state.balance;
const expensive = await request('/api/items?min=10000&limit=1');
await request('/api/state', { type: 'upgrade', extra: 1, target: expensive.items[0].id, chance: .75 }, 400);
current = await request('/api/state');
assert.equal(current.state.balance, beforeInvalid, 'Invalid chance must not charge balance');
const sell = current.state.inventory[0];
current = await request('/api/state', { type: 'sell', ids: [sell.uid] });
assert.equal(current.state.balance, beforeInvalid + sell.value);
assert.ok(!current.state.inventory.some(i => i.uid === sell.uid));
const count = current.state.inventory.length;
const acquired = current.state.progress.acquired;
const stats = current.state.progress.stats;
assert.equal(stats.upgradeAttempts, 5);
current = await request('/api/state', { type: 'reset' });
assert.equal(current.state.balance, 0);
assert.equal(current.state.coins, 0);
assert.equal(current.state.inventory.length, count);
assert.deepEqual(current.state.progress.stats, stats);
assert.deepEqual(current.state.progress.acquired, acquired);
assert.equal(current.state.progress.title, 'Тестовая витрина');
console.log('PASS: all pages and covers, price bounds, delayed top-up, exact chances, skin stake, opening, sale, reset, protected-item rollback, showcase persistence, appearance validation, statistics and acquisition history.');
await request('/api/state', { type: 'topup', amount: 50000 });
const resetSnapshot = JSON.stringify((await request('/api/state')).state);
await request('/api/state', { type: 'resetAll' }, 400);
assert.equal(JSON.stringify((await request('/api/state')).state), resetSnapshot);
const resetId = crypto.randomUUID();
current = await request('/api/state', { type: 'resetAll', confirmReset: true, requestId: resetId });
assert.equal(current.state.balance, 0); assert.equal(current.state.coins, 0); assert.equal(current.state.pending, null);
assert.equal(current.state.opens, 0); assert.deepEqual(current.state.inventory, []); assert.deepEqual(current.state.history, []);
assert.deepEqual(current.state.progress.acquired, []); assert.deepEqual(current.state.progress.achievements, []);
assert.deepEqual(current.state.progress.locked, []); assert.deepEqual(current.state.progress.showcase, []);
assert.equal(current.state.progress.title, 'Моя коллекция'); assert.equal(current.state.progress.frame, 'plain'); assert.equal(current.state.progress.background, 'carbon');
assert.equal(current.state.progress.stats.caseOpens, 0); assert.equal(current.state.progress.stats.upgradeAttempts, 0); assert.equal(current.state.progress.stats.bestDrop, null); assert.deepEqual(current.state.progress.stats.rounds, []);
assert.deepEqual(current.lookup, {});
const cleared = current.state;
assert.deepEqual((await request('/api/state')).state, cleared, 'Reset persists after reload');
await request('/api/state', { type: 'topup', amount: 12345 });
current = await request('/api/state', { type: 'resetAll', confirmReset: true, requestId: resetId });
assert.equal(current.result.duplicate, true); assert.equal(current.state.pending.amount, 12345);
console.log('PASS: closest higher upgrade chances and confirmed full reset with persistence, cancelled deposit and replay protection.');
